import { Box } from '@chakra-ui/react';
import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data } = trpc.useQuery(['users.getAllUsernames']);

  return (
    <>
      <Head>
        <title>Guestbook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box minWidth="max-content">
        {!data && <p>loading...</p>}
        {data?.length &&
          data.map((user) => <p key={user.username}>{user.username}</p>)}
      </Box>
    </>
  );
};

export default Home;
